### ISSUE TITLE
Deleted Parent Comment Error

### ISSUE THREAD

**Issue by joegoldbeck** [techforwarren/warren-plan-bot#139]
https://console.cloud.google.com/errors/CKLYyPHx1tGgzQE?time=P7D&project=wpb-prod

`praw.exceptions.APIException: DELETED_COMMENT: 'that comment has been deleted' on field 'parent'`

**Comment by Hucxley** [comment]
I think we just need to have a catch for deleted comments.  In fairness, it may have been deleted in between the keyword and replying. Since the bot runs on a loop a few times each time it activates, a person may have typed in a trigger phrase, and then changed their mind and reposted during the function run.
