### ISSUE TITLE
Add an operation for replying to a parent comment

### ISSUE THREAD

**Issue by joegoldbeck** [techforwarren/warren-plan-bot#82]
So someone can call the Reddit Bot to reply to _someone else's_ comment.

Spec: 

- Feature can be activated it with the following command-line style flag

      `!warrenplanbot --tell-parent climate change`

- When getting the trigger line, remove the flag so it doesn’t interfere with downstream matching
- Reply to the _parent_ comment instead of the comment that triggered us, when flag is detected
- The post record should stay largely the same, and continue to mostly refer to the comment that triggered us. However, when someone is using the `--tell-parent` feature, we should _additionally_ include
  - Parent comment text
  - Parent comment permalink
- Reply also to the comment that triggered the bot with something like "Sure" or "I'd be happy to!" or ....

**Comment by Hucxley** [comment]
use case:

User X posts a comment that they like some things about Sen. Warren, but aren't sure about how she will handle $Issue.

User Y replies to User X with "!warrenplanbot URL to User X comment what is Sen. Warren's plan for $Issue?"

Bot replies to User X's original comment with a plan (or cluster) that scores above the threshold (!important) to provide User X with more info about Warren's position on $Issue.

**Comment by Hucxley** [comment]
Bumping this because I think it's about time.  A large volume of the bot's usage is to answer another poster's "curiosity" about her position about something.  Problem is, the curious person doesn't get the response, the person who triggers the bot does, and the alert doesn't bubble up.  See [here](https://www.reddit.com/r/ElizabethWarren/comments/dbb7op/will_voters_support_elizabeth_warrens_trade/f21v3se/?context=3) for a model example of this.

I think this should be an operation that requires a very specific initiator to ensure it doesn't get called on accident.  Something like "!warrentplanbot tell $urlToRespondTo about" standard topic request phrase.

We need to look at how a url to another comment appears in the comment text.  Is it in markdown, is it plain text, or does it just display the text shown and not the url?

**Comment by joegoldbeck** [comment]
I don't think there's any reason the person would need to post a url in the comment, as you point out, it's going to look weird.

Anyway, _we can retrieve the parent comment and then reply to it directly via the PRAW API_. User should just need to say something like

`!WarrenPlanBot replytoparent what is her plan for climate change`, and we can take care of the rest on the backend.

Not sure what would be an evocative command, such that people would remember it and not misspell it

**Comment by joegoldbeck** [comment]
I don't _think_ we want to give people the ability to have the planbot reply to arbitrary comments, just their parent, right?

I feel like weird stuff could happen if we allow someone to call the bot to "arbitrary comment on /r/ewarren"

**Comment by Hucxley** [comment]
@joegoldbeck that's actually why I thought to include the URL because you can check the URL they use in the operation call and check it against the parent comment, permalink for the calling comment, and comment ID for the  calling comment to make sure that the URL request is being "aimed" correctly within the comment chain.  It's more of a safety net to prevent abuse, basically.  It's not foolproof, but it's close.

Also, sometimes the "parent" is a submission, sometimes it's another comment.  You have to get into the t1, t2, t3, etc parts of PRAW to know what level a comment lives in.  But, if you have a URL in the operation call, you can walk through the levels with regex match between the URL and the calling comment properties you get from PRAW or Pushshift.

**Comment by joegoldbeck** [comment]
Oh ok. I think I see what you’re getting at with the url

For getting the parent, I actually don’t think it’s very hard to deal with whether the parent is a submission vs comment. You can just call .parent on the comment and then check the data type that PRAW returns. No need to get into t3 t5 etc...

**Comment by joegoldbeck** [comment]
If I’m understanding correctly, you’re saying that we intentionally make it harder for someone to have use reply to a comment parent, in order to prevent abuse. Is that right?

I kind of think if we do that,

1) either no one will use it if it’s complex, or worse, they’ll use it wrong and think it’s broken (for ex, they won’t fully realize they have to reply to the comment itself because logically if they put the url that shouldn’t be necessary). For ex, we’ve already had folks think that maybe their query needs to end in a “?” because it was slow the respond and they were looking for a logical reason

2) do we need to worry about this given that we’re on a friendly subreddit? I’d think abuse is something that the mods could punish / they wouldn’t punish the bot for it. We could keep an eye out for downvoted posts, certainly. And if folks start to abuse it we could do something to make it harder or remove the feature

**Comment by joegoldbeck** [comment]
I kind of think we should do this like command line args. So

‘!warrenplanbot -p climate change’
‘!warrenplanbot —parent climate change’

Familiar, simple to use, hard to fat finger familiar

**Comment by opoku** [comment]
As I work on this, I’m considering changing this contract: https://github.com/techforwarren/warren-plan-bot/blob/master/src/matching.py#L35-L43 so that its the body of the trigger text only that is passed into the `Strategy` and `RuleStrategy` instead of the actual `post` object. This will make it easier to extract out the `parent` and other future flags before passing calling the various `Strategy` functions. Thoughts?

**Comment by joegoldbeck** [comment]
Would prefer to keep all of it, personally. We’re not currently using the rest of the context in our matching logic, but we definitely might!

**Comment by joegoldbeck** [comment]
I do see how it would be nice to simplify that though! 

You could pass both in, perhaps? Keep the post itself as an optional arg or a kwarg

**Comment by joegoldbeck** [comment]
Closed by #144
